---
title: "Practica MLG"
author: "Arnau Nualart i Montse Garcia"
date: "15/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(car)
library(MASS)
library(AER)
library(effects)
library(lmtest)
library(FactoMineR)
library(rms)
library(fmsb)
library(ROCR)
library(AUC)
```


# Importació Dades i Neteja

```{r}
data <- read.csv("D:/Universitat/Cuart de carrera/Models Lineals Generalitzats/PRACTICA/Dades-20221215/data.csv", sep=";")
head(data)
data$visita<- factor(data$vis_bin, labels=c("No", "Si"))
data$educacio<- factor(data$educacio, labels=c("primaris", "secundaris", "univ.", "post_univ."))
data$treball<- factor(data$treball, labels= c("No", "Si"))
data$dona<- factor(data$dona, labels=c("no", "si"))
data$casat<- factor(data$casat, labels = c("no", "si"))
data$autonom<- factor(data$autonom, labels=c("no","si"))
data$c.edat <- cut(data$edat,breaks=c(24,34,44,54,65))   
data$c.ingressos<- cut(data$ingressos, breaks= c(-1,2,3,4,25))
data$id<- NULL
data$temps<- factor(data$temps, labels=c("1 any", "2 anys", "3 anys", "4 anys", "5 anys"))
```
#Descriptiva de les Dades

## Descriptiva Univariant de les variables

```{r}
summary(data)
```
Mirem si les noves variables categoritzades estan ben balancejades

```{r}
par(mfrow=c(1,2),las=2)
barplot(table(data$c.edat))
barplot(table(data$c.ingressos))

```

Gràfic Bivariant descriptiu de les variables explicatives amb vis_num

```{r}
par(mfrow=c(1,2),las=1)
Boxplot(edat~vis_num,data=data,col=c(2,3))
Boxplot(ingressos~vis_num,data=data,col=c(2,3))

par(mfrow=c(3,3),las=1)
plot(vis_num~temps,data=data,col=c(2,3))
plot(vis_num~educacio,data=data,col=c(2,3))
plot(vis_num~treball,data=data,col=c(2,3))
plot(vis_num~dona,data=data,col=c(2,3))
plot(vis_num~casat,data=data,col=c(2,3))
plot(vis_num~autonom,data=data,col=c(2,3))
plot(vis_num~c.edat,data=data,col=c(2,3))
plot(vis_num~c.ingressos,data=data,col=c(2,3))
```


Gràfic Bivariant descriptiu de les variables explicatives amb vis_bin


```{r}
par(mfrow=c(1,2),las=1)
Boxplot(edat~visita,data=data,col=c(2,3))
Boxplot(ingressos~visita,data=data,col=c(2,3))

par(mfrow=c(3,3),las=1)
plot(visita~temps,data=data,col=c(2,3))
plot(visita~educacio,data=data,col=c(2,3))
plot(visita~treball,data=data,col=c(2,3))
plot(visita~dona,data=data,col=c(2,3))
plot(visita~casat,data=data,col=c(2,3))
plot(visita~autonom,data=data,col=c(2,3))
plot(visita~c.edat,data=data,col=c(2,3))
plot(visita~c.ingressos,data=data,col=c(2,3))
```
